version: '3.8'

services:
  mindie-gateway:
    build: 
      context: .
      dockerfile: dockerfile
    image: mindie-gateway
    container_name: mindie-gateway
    ports:
      - "80:80"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
